# Generated by Django 2.0 on 2017-12-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0002_auto_20171217_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='id',
        ),
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
