# Generated by Django 2.0 on 2017-12-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0003_auto_20171218_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='race',
            new_name='race_name',
        ),
        migrations.RenameField(
            model_name='racetrait',
            old_name='race',
            new_name='race_name',
        ),
    ]
