# Generated by Django 2.0 on 2017-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0004_auto_20171218_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racetrait',
            name='id',
        ),
        migrations.AlterField(
            model_name='racetrait',
            name='trait_name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
