# Generated by Django 2.0 on 2017-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0005_auto_20171219_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetrait',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racetrait',
            name='trait_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
