# Generated by Django 2.0 on 2017-12-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0006_auto_20171219_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='agility_modifier',
            new_name='dexterity_modifier',
        ),
    ]
