# Generated by Django 2.0 on 2018-01-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0007_auto_20171219_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('hit_die', models.IntegerField(default=0)),
                ('skill_choice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(default='', max_length=20)),
                ('proficiency_type', models.CharField(default='', max_length=20)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proficiency', to='character_builder.Class')),
            ],
        ),
        migrations.CreateModel(
            name='SavingThrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=5)),
                ('long_name', models.CharField(default='', max_length=20)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savingthrow', to='character_builder.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=20)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='character_builder.Class')),
            ],
        ),
    ]
