# Generated by Django 2.0 on 2018-01-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0008_class_proficiency_savingthrow_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='skill_choice',
            new_name='from_skills_choose',
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='character_builder.Class'),
        ),
        migrations.AlterField(
            model_name='savingthrow',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saving_throws', to='character_builder.Class'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='character_builder.Class'),
        ),
    ]
