# Generated by Django 2.0 on 2018-01-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0009_auto_20180101_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(default='', max_length=20)),
                ('_class', models.CharField(default='', max_length=20)),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('hit_die', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_languages', to='character_builder.Race'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_proficiencies', to='character_builder.Class'),
        ),
        migrations.AddField(
            model_name='racetrait',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_race_traits', to='character_builder.Race'),
        ),
        migrations.AddField(
            model_name='savingthrow',
            name='character_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_saving_throws', to='character_builder.Class'),
        ),
        migrations.AddField(
            model_name='skill',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='character_builder.Class'),
        ),
        migrations.AlterField(
            model_name='language',
            name='race_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='character_builder.Race'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='character_builder.Class'),
        ),
        migrations.AlterField(
            model_name='racetrait',
            name='race_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_traits', to='character_builder.Race'),
        ),
        migrations.AlterField(
            model_name='savingthrow',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saving_throws', to='character_builder.Class'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='character_builder.Class'),
        ),
    ]
