# Generated by Django 2.0 on 2018-01-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0010_auto_20180104_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
