# Generated by Django 2.0 on 2018-01-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0011_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_languages', to='character_builder.Character'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_proficiencies', to='character_builder.Character'),
        ),
        migrations.AlterField(
            model_name='racetrait',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_race_traits', to='character_builder.Character'),
        ),
        migrations.AlterField(
            model_name='savingthrow',
            name='character_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_saving_throws', to='character_builder.Character'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='character_builder.Character'),
        ),
    ]
